language: objective-c

cache:
  directories:
    - /Library/Caches/Homebrew

install:
  - mv * .[!.]* /usr/local
  - cd /usr/local
  - git clean -fd

script:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
        brew test-bot $TRAVIS_COMMIT --skip-setup --verbose;
    else
        brew test-bot $TRAVIS_COMMIT --skip-setup --verbose --ci-pr;
    fi

notifications:
  email: false
