language: objective-c

cache:
  directories:
    - /Library/Caches/Homebrew

install:
  - mkdir -p /tmp/oldbrew
  - mv /usr/local/* /usr/local/.[!.]* /tmp/oldbrew
  - mv * .[!.]* /usr/local

script:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
        brew test-bot $TRAVIS_COMMIT --skip-setup --verbose;
    else
        brew test-bot $TRAVIS_COMMIT --skip-setup --verbose --ci-pr;
    fi

notifications:
  email: false
